#define ZF_LOG_LEVEL ZF_LOG_INFO
#include <zf_log.h>
#include <time.h>

static void log_some()
{
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
	ZF_LOGI("Lorem ipsum dolor sit amet");
	time(0);
}

int main(int argc, char *argv[])
{
	(void)argc; (void)argv;
	log_some();
	return 0;
}
