#define ZF_LOG_LEVEL ZF_LOG_INFO
#include <zf_log.h>
#include <time.h>

int g_int1;
int g_int2;
char *g_str1;
char *g_str2;
void *g_p1;
void *g_p2;

static void log_some()
{
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
	ZF_LOGI("%i-%i/%s-%s/%p-%p", g_int1, g_int2, g_str1, g_str2, g_p1, g_p2);
	time(0);
}

int main(int argc, char *argv[])
{
	(void)argc; (void)argv;
	log_some();
	return 0;
}
